//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DertInfo.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DertInfo.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;ql-align-center&quot;&gt;&lt;img src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAACACAYAAAB9V9ELAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4gkQEBAEm9hQ/wAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAfE0lEQVR42u3deZAcV50n8O/Lq86u6kN9qlv3YbVkHZaxbGN8rDmNbS7D4IEBjPEuELPDMBsEwW7sTuzCbsAMBJdthmNgOMwOxxgzmBmCBdv4xpYPydZhHa1WH+pDfdVdlef+0ZJCRlKrql7W0V3fT4QDh+l8mfXey3y/zHz5e+LLD13hgYiIiBqKwiogIiJiAEBEREQMAIiIiIgBABERETEAICIiIgYARERExACAiIiIGAAQERERAwAiIiJiAEBEREQMAIiIiIgBABERE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailTemplate_Event_Cancel_Default {
            get {
                return ResourceManager.GetString("EmailTemplate_Event_Cancel_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;ql-align-center&quot;&gt;&lt;img src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAACACAYAAAB9V9ELAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4gkQEBAEm9hQ/wAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAfE0lEQVR42u3deZAcV50n8O/Lq86u6kN9qlv3YbVkHZaxbGN8rDmNbS7D4IEBjPEuELPDMBsEwW7sTuzCbsAMBJdthmNgOMwOxxgzmBmCBdv4xpYPydZhHa1WH+pDfdVdlef+0ZJCRlKrql7W0V3fT4QDh+l8mfXey3y/zHz5e+LLD13hgYiIiBqKwiogIiJiAEBEREQMAIiIiIgBABERETEAICIiIgYARERExACAiIiIGAAQERERAwAiIiJiAEBEREQMAIiIiIgBABERE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailTemplate_Registration_Confirm_Default {
            get {
                return ResourceManager.GetString("EmailTemplate_Registration_Confirm_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;ql-align-center&quot;&gt;&lt;img src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAACACAYAAAB9V9ELAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4gkQEBAEm9hQ/wAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAfE0lEQVR42u3deZAcV50n8O/Lq86u6kN9qlv3YbVkHZaxbGN8rDmNbS7D4IEBjPEuELPDMBsEwW7sTuzCbsAMBJdthmNgOMwOxxgzmBmCBdv4xpYPydZhHa1WH+pDfdVdlef+0ZJCRlKrql7W0V3fT4QDh+l8mfXey3y/zHz5e+LLD13hgYiIiBqKwiogIiJiAEBEREQMAIiIiIgBABERETEAICIiIgYARERExACAiIiIGAAQERERAwAiIiJiAEBEREQMAIiIiIgBABERE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailTemplate_Registration_Submit_Default {
            get {
                return ResourceManager.GetString("EmailTemplate_Registration_Submit_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EventDefaultImage {
            get {
                object obj = ResourceManager.GetObject("EventDefaultImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GroupDefaultImage {
            get {
                object obj = ResourceManager.GetObject("GroupDefaultImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
