namespace DertInfo.Models.System.Enumerations
{
    public enum CompetitionFlowState
    {
        New = 1,
        Generated = 3,
        Populated = 2,
        Published = 4
    };
}

/* New - the competition has been created but has had no attendance assosiations */
/* Generated - the competition has had it's dances generated by the system. Must be after population*/
/* Populated - the process to attach interested parties as competition entrants has been completed */
/* Published - the results of this compeition have been published and no further changes should be permitted */
