name: Deploy .NET to Azure App Service

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      target_app:
        required: true
        type: string
      package_path:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      app_type:
        required: false
        type: string
        default: webApp

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - uses: azure/login@v2
        with:
          client-id: ${{ inputs.environment == 'prod' && vars.AZURE_ENTRA_OIDC_CLIENTID_PRD || vars.AZURE_ENTRA_OIDC_CLIENTID_STG }}
          tenant-id: ${{ inputs.environment == 'prod' && vars.AZURE_ENTRA_OIDC_TENANTID_PRD || vars.AZURE_ENTRA_OIDC_TENANTID_STG }}
          subscription-id: ${{ inputs.environment == 'prod' && vars.AZURE_SUBSCRIPTION_DEPLOY_SUBSCRIPTIONID_PRD || vars.AZURE_SUBSCRIPTION_DEPLOY_SUBSCRIPTIONID_STG }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.environment == 'prod' && (inputs.target_app == 'api' && vars.AZURE_WEBAPP_API_RESOURCENAME_PRD || vars.AZURE_FUNCTIONAPP_FUNCTIONS_RESOURCENAME_PRD) || (inputs.target_app == 'api' && vars.AZURE_WEBAPP_API_RESOURCENAME_STG || vars.AZURE_FUNCTIONAPP_FUNCTIONS_RESOURCENAME_STG) }}
          package: ${{ inputs.package_path }}
          type: ${{ inputs.app_type }}
