name: Deploy .NET to Azure App Service

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      package_path:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      app_type:
        required: false
        type: string
        default: webApp
    secrets:
      APP_NAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_NAME }}
          package: ${{ inputs.package_path }}
          type: ${{ inputs.app_type }}
