name: App CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/dert-app/**'
      - 'package.json'
      - '.github/workflows/app-ci.yml'
  pull_request:
    paths:
      - 'apps/dert-app/**'
      - 'package.json'
      - '.github/workflows/app-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install
        run: npm install
        working-directory: apps/dert-app/src/client

      - name: Lint
        run: npm run lint
        working-directory: apps/dert-app/src/client
        continue-on-error: true

      - name: Test
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: apps/dert-app/src/client
        continue-on-error: true

      - name: Build
        run: npm run build
        working-directory: apps/dert-app/src/client
