name: App CD

on:
  push:
    branches: [main]
    paths:
      - 'apps/dert-app/**'
      - 'package.json'
      - '.github/workflows/app-cd.yml'
      - '.github/workflows/reusable-build-push-docker.yml'
      - '.github/workflows/reusable-deploy-static-web-app.yml'

concurrency:
  group: app-cd-test
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/reusable-build-push-docker.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      dockerfile: apps/dert-app/Dockerfile
      context: apps/dert-app
      image_repository: dertinfo/dertinfo-app

  deploy-test:
    uses: ./.github/workflows/reusable-deploy-static-web-app.yml
    with:
      environment: test
      workload: app
      app_location: apps/dert-app/src/client
      output_location: dist
      build_command: npm run ado-build-ui-test
      submodules: true
