name: Web CD

on:
  push:
    branches: [main]
    paths:
      - 'apps/dert-web/**'
      - 'package.json'
      - '.github/workflows/web-cd.yml'
      - '.github/workflows/reusable-build-push-docker.yml'
      - '.github/workflows/reusable-deploy-static-web-app.yml'

concurrency:
  group: web-cd-test
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/reusable-build-push-docker.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      environment: test
      dockerfile: apps/dert-web/Dockerfile
      context: apps/dert-web
      image_repository: dertinfo/dertinfo-web

  deploy-test:
    uses: ./.github/workflows/reusable-deploy-static-web-app.yml
    secrets: inherit
    with:
      environment: test
      workload: web
      app_location: apps/dert-web/src/client
      api_location: apps/dert-web/src/functions
      output_location: dist
      build_command: npm run ado-build-ui-test
      submodules: true
